# Generated by Django 4.2.7 on 2026-01-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='markdown_content',
            field=models.TextField(blank=True, help_text='Additional project details in Markdown format'),
        ),
    ]
