# Generated by Django 4.2.7 on 2026-01-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_markdown_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='Key features of the project (one per line or comma-separated)'),
        ),
    ]
